a.out: nd.o rd.o sd.o bd.o db.o scf.o
	gcc nd.o sd.o bd.o db.o scf.o rd.o
nd.o: nd.c
	gcc -c nd.c
rd.o: rd.c
	gcc -c rd.c
sd.o: sd.c
	gcc -c sd.c
bd.o: bd.c
	gcc -c bd.c
db.o: db.c
	gcc -c db.c
scf.o: scf.c
	gcc -c scf.c
